swagger: '2.0'

info:
  version: "0.0.1"
  title: Course Subjects API

paths:
  /subjects:
    get:
      tags:
       - organizations
       - departments
      description: "Gets all `course-subject` objects."
      operationId: getCourseSubjects
      produces:
        - application/json
      summary: Get information
      parameters:
        - $ref: '#/parameters/pretty'
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObjects"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"

  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"

  Attributes:
    properties:
      abbreviation:
        type: string
        description: "This code is used to filter the list of courses. Example values: 'CS', 'BIO', 'PH'"
      title:
        type: string
        description: "Human readable course title. Example values: 'Computer Science', 'Biology-UO', 'Physics'"

  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string
        description: Name of the API.
      time:
        type: string
        description: Build time in ISO 8601 format.
      unixTime:
        type: integer
        description: Build time as milliseconds since the unix epoch.
      commit:
        type: string
        description: Git commit hash of the revision which was built.
      documentation:
        type: string
        description: Filename of the swagger specification for the API.
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
